### ISSUE TITLE
Using estdlib in platformio

### ISSUE THREAD

**Issue by seanngpack** [malachi-iot/estdlib#1]
Hi, I'd like to use your library in platformIO, more specifically utilize the cstddef header bundled in the library. Are there any examples on how to use this in platformIO?

**Comment by malachib** [comment]
@seanngpack Hi, technically a partial yes with:

https://github.com/malachi-iot/estdlib/tree/dev/test/arduino/basic

That hasn't been tested in a while however.  If that doesn't get you going hit me with your specifics and we'll come up with a solution

**Comment by malachib** [comment]
Hi @seanngpack 

Give https://github.com/malachi-iot/estdlib/tree/dev/examples/pio/string a try see how that works out for you

**Comment by malachib** [comment]
Made some revisions, this one is a better fit for you:

https://github.com/malachi-iot/estdlib/blob/master/test/unity/cstddef.cpp

What environment/MCU are you using?
